"""initial schema

Revision ID: bcc935582a1a
Revises: 
Create Date: 2026-06-08 03:27:27.026022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc935582a1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rule',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('project_pattern', sa.String(length=255), nullable=False),
    sa.Column('spider_pattern', sa.String(length=255), nullable=False),
    sa.Column('thresholds_json', sa.Text(), nullable=True),
    sa.Column('on_finished', sa.Boolean(), nullable=True),
    sa.Column('on_running_interval', sa.Integer(), nullable=True),
    sa.Column('channels_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deploy_record',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('project', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.Column('eggname', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('repo_id', sa.BigInteger(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('results_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deploy_repo',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('repo_url', sa.String(length=512), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('project', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('webhook_secret', sa.String(length=64), nullable=False),
    sa.Column('nodes_json', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('job_stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('server', sa.String(length=255), nullable=False),
    sa.Column('project', sa.String(length=255), nullable=False),
    sa.Column('spider', sa.String(length=255), nullable=False),
    sa.Column('job', sa.String(length=255), nullable=False),
    sa.Column('ext', sa.String(length=16), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('pages', sa.BigInteger(), nullable=True),
    sa.Column('items', sa.BigInteger(), nullable=True),
    sa.Column('runtime', sa.String(length=20), nullable=True),
    sa.Column('finish_reason', sa.String(length=64), nullable=True),
    sa.Column('first_log_time', sa.String(length=19), nullable=True),
    sa.Column('latest_log_time', sa.String(length=19), nullable=True),
    sa.Column('stats_json', sa.Text(), nullable=True),
    sa.Column('alert_state', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server', 'project', 'spider', 'job')
    )
    op.create_index(op.f('ix_job_stats_server'), 'job_stats', ['server'], unique=False)
    op.create_table('job_version',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('server', sa.String(length=255), nullable=False),
    sa.Column('project', sa.String(length=255), nullable=False),
    sa.Column('spider', sa.String(length=255), nullable=False),
    sa.Column('job', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server', 'project', 'job')
    )
    op.create_index(op.f('ix_job_version_server'), 'job_version', ['server'], unique=False)
    op.create_table('metadata',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('last_check_update_timestamp', sa.Float(), nullable=True),
    sa.Column('main_pid', sa.Integer(), nullable=True),
    sa.Column('logparser_pid', sa.Integer(), nullable=True),
    sa.Column('poll_pid', sa.Integer(), nullable=True),
    sa.Column('pageview', sa.Integer(), nullable=False),
    sa.Column('url_scrapydweb', sa.Text(), nullable=False),
    sa.Column('url_jobs', sa.String(length=255), nullable=False),
    sa.Column('url_schedule_task', sa.String(length=255), nullable=False),
    sa.Column('url_delete_task_result', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('scheduler_state', sa.Integer(), nullable=False),
    sa.Column('jobs_per_page', sa.Integer(), nullable=False),
    sa.Column('tasks_per_page', sa.Integer(), nullable=False),
    sa.Column('jobs_style', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('setting',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('task',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('trigger', sa.String(length=8), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('project', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=False),
    sa.Column('spider', sa.String(length=255), nullable=False),
    sa.Column('jobid', sa.String(length=255), nullable=False),
    sa.Column('settings_arguments', sa.Text(), nullable=False),
    sa.Column('selected_nodes', sa.Text(), nullable=False),
    sa.Column('year', sa.String(length=255), nullable=False),
    sa.Column('month', sa.String(length=255), nullable=False),
    sa.Column('day', sa.String(length=255), nullable=False),
    sa.Column('week', sa.String(length=255), nullable=False),
    sa.Column('day_of_week', sa.String(length=255), nullable=False),
    sa.Column('hour', sa.String(length=255), nullable=False),
    sa.Column('minute', sa.String(length=255), nullable=False),
    sa.Column('second', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.String(length=19), nullable=True),
    sa.Column('end_date', sa.String(length=19), nullable=True),
    sa.Column('timezone', sa.String(length=255), nullable=True),
    sa.Column('jitter', sa.Integer(), nullable=False),
    sa.Column('misfire_grace_time', sa.Integer(), nullable=True),
    sa.Column('coalesce', sa.String(length=5), nullable=False),
    sa.Column('max_instances', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('task_result',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('execute_time', sa.DateTime(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_result_task_id'), 'task_result', ['task_id'], unique=False)
    op.create_table('task_job_result',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_result_id', sa.BigInteger(), nullable=False),
    sa.Column('run_time', sa.DateTime(), nullable=False),
    sa.Column('node', sa.Integer(), nullable=False),
    sa.Column('server', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=9), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['task_result_id'], ['task_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_job_result_node'), 'task_job_result', ['node'], unique=False)
    op.create_index(op.f('ix_task_job_result_task_result_id'), 'task_job_result', ['task_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_job_result_task_result_id'), table_name='task_job_result')
    op.drop_index(op.f('ix_task_job_result_node'), table_name='task_job_result')
    op.drop_table('task_job_result')
    op.drop_index(op.f('ix_task_result_task_id'), table_name='task_result')
    op.drop_table('task_result')
    op.drop_table('user')
    op.drop_table('task')
    op.drop_table('setting')
    op.drop_table('metadata')
    op.drop_index(op.f('ix_job_version_server'), table_name='job_version')
    op.drop_table('job_version')
    op.drop_index(op.f('ix_job_stats_server'), table_name='job_stats')
    op.drop_table('job_stats')
    op.drop_table('deploy_repo')
    op.drop_table('deploy_record')
    op.drop_table('alert_rule')
    # ### end Alembic commands ###
